In [ ]:
# Numpy is used to hold the large amount of data which is not possible for python (weather report data, stockmarket data) 
# for install we used (!pip install numpy)

In [1]:
import numpy as np

In [2]:
x1 = ([[1,2,3,4],[5,6,7,8]])
arr_1 = np.array(x1)
print(arr_1)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
#it show the shape present in the row or columns
arr_1.shape

(2, 4)

In [72]:
reshaped_arr = arr_2.reshape
print(reshaped_arr)

<built-in method reshape of numpy.ndarray object at 0x00000174E9E45470>


In [9]:
# it show the type to dimensional 
arr_1.ndim

2

In [55]:
# this is 3 dimensional array
arr3 = np.array([[[1, 2,5], [3, 4,11], [5, 6,12], [7, 8,16]]])
print(arr3)
print("Number of dimensions -",arr3.ndim)

[[[ 1  2  5]
  [ 3  4 11]
  [ 5  6 12]
  [ 7  8 16]]]
Number of dimensions - 3


In [53]:
#its show the size the present of number in the array
arr_1.size

8

In [19]:
arr3.size

12

In [26]:
sum_1 = np.sum(arr3)
sum_1

np.int64(80)

In [27]:
max_1 = np.max(arr3)
max_1

np.int64(16)

min_1 = np.min(arr3)
min_1

In [36]:
arr3.dtype

dtype('int64')

In [37]:
mean_1 = np.mean(arr3)
mean_1

np.float64(6.666666666666667)

In [45]:
x2 = [2, 4, 6, 8, 10]
arr_2 = np.array(x2)
arr_2

array([ 2,  4,  6,  8, 10])

In [44]:
mean_2 = np.mean(arr_2)
mean_2

np.float64(6.0)

In [60]:
#perform vector operation 
x4 = [2,3,4,5,6]
arr_4 = np.array(x4)
print(arr_4 * 2)
print(arr_4 + 12)

[ 4  6  8 10 12]
[14 15 16 17 18]


In [68]:
#perform vector operation
x = [[1,2,3],[7,8,9]]
x2 = [[4,5,6],[4,5,6]]
a_arr = np.array(x)
n_arr1 = np.array(x2)
a_arr+n_arr1

array([[ 5,  7,  9],
       [11, 13, 15]])

In [63]:
#matrixs
matrixs = np.array([[4,5,6],[7,8,9]])
print(matrixs.T)

[[4 7]
 [5 8]
 [6 9]]


In [ ]:
#questio to solve

In [5]:
#trying to remove the values(sum,mean,max,min) of each rows separetly 
x5 = [[[1, 2 ,3],
[4, 5, 6],
[7, 8, 9]]]
arr_5 = np.array(x5)
mean_2 = np.mean(arr_5)
mean_2

np.float64(5.0)

In [19]:
#This is used to print a single row when multiple rows are present
print(arr_5[0,2,:2])

[7 8]


In [38]:
print(arr_5[0,2])

[7 8 9]


In [31]:
print( arr_5[0,2])

[7 8 9]


In [43]:
#This is used to compute the sum, mean, maximum, and minimum of each row separately.
mean = np.mean (arr_5[0,2])
mean

np.float64(8.0)

In [42]:
sum_1 = np.sum(arr_5[0,2])
sum_1

np.int64(24)

In [45]:
max_1 = np.max(arr_5[0,1])
max_1

np.int64(6)

In [6]:
import numpy as np
min_1 = np.min(arr_5[0,2])
min_1

np.int64(7)

In [1]:
import numpy as np

In [11]:
x = [2,4,5,6,8]
x1 = [1001,1002,1003,1004,1005]
arr_1 = np.array(x)
arr_2 = np.array(x1)

In [12]:
arr_2

array([1001, 1002, 1003, 1004, 1005])

In [6]:
st_1 = np.std(arr_1)
st_1

np.float64(2.0)

In [14]:
st_2 = np.std(arr_2)
st_2

np.float64(1.4142135623730951)