In [1]:
# numpy
import numpy as np

In [13]:
24/10/2025
# arrange (start, stop,step, datatype = none)
data = np.arange(0,10,2, dtype = int)
dt = np.arange(10,0,-3)
print(data)
print(dt)

[0 2 4 6 8]
[10  7  4  1]


In [26]:
# linespace (start , stop,num=5, endpoint = True, retstep = False, dtype = none)
data = np.linspace(0,10,5, endpoint = True, retstep = False)
print(data)

[ 0.   2.5  5.   7.5 10. ]


In [22]:
# logspace (start, stop,step, base= none)
dat = np.logspace(1,10,4, base = 10)
print(dat)

dat1 = np.logspace(1,10,4)
print(dat1)

[1.e+01 1.e+04 1.e+07 1.e+10]
[1.e+01 1.e+04 1.e+07 1.e+10]


In [ ]:
# arrange (start, stop,step, datatype = none)
data = np.arange(0,10,2, dtype = int)
dt = np.arange(10,0,-3)
print(data)
print(dt)


# logspace (start, stop,step, base= none)
dat = np.logspace(1,10,4, base = 10)
print(dat)

# logspace (start, stop,step, base= none)
dat = np.logspace(1,10,4, base = 10)
print(dat)
